---
 # Hashicorp boxes are used by default as per vms.yaml, but there are options
 # for other boxes in the boxes.yaml file.
vms:
  #======================================#
  # Puppet Master machine                #
  #======================================#
  - name: master.inf.puppet.vm
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - master
      - el_base
      - el_stop_firewall
      - trusted_fact_puppet_master

  #======================================#
  # Conjur Secrets Server machine        #
  #======================================#
  - name: conjur-master.puppet.vm
    box: puppetlabs/ubuntu-14.04-64-nocm
    roles:
      - pe_agent
      - el_base
      - trusted_fact_conjur_master

  #======================================#
  # managed node machine                 #
  #======================================#
  - name: conjur-pe-node.puppet.vm
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe_agent
      - el_base
      - trusted_fact_conjur_pe_node

  #======================================#
  # Gitlab machine                       #
  #======================================#
  - name: gitlab.inf.puppet.vm
    box: puppetlabs/centos-7.2-64-nocm
    roles:
      - pe_agent
      - el_base
      - trusted_fact_gitlab
    providers:
      - type: virtualbox
        customize:
          - [modifyvm, !ruby/sym id, '--memory', 1024]
